### ISSUE TITLE
Test package names dont seem right

### ISSUE THREAD

**Issue by idkjs** [planado/reason-commons#4]
Just an FYI. Thanks for sharing this.

Looks like the generated lib files are ` Cannot find module 'bs-platform/lib/js/list.js' from 'jest.js'` rather than the list.js file jest is looking for. Also, directory its looking up seems incorrect.

Running `npm run start` then `npm run test` gets you this error:

```sh
 FAIL  lib/js/__tests__/array_test.js
  ● Test suite failed to run

    Cannot find module 'bs-platform/lib/js/list.js' from 'jest.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/bs-jest/lib/js/src/jest.js:3:31)

 FAIL  lib/js/__tests__/list_test.js
  ● Test suite failed to run

    Cannot find module 'bs-platform/lib/js/list.js' from 'jest.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/bs-jest/lib/js/src/jest.js:3:31)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.444s
Ran all test suites.

Watch Usage: Press w to show more.
```
- tree
```sh

$ tree -h lib/
lib/
├── [ 340]  bs
│   ├── [ 578]  __tests__
│   │...  
│   └── [1.2K]  src
│   │...  
└── [ 136]  js
    ├── [ 170]  __tests__
    │   ├── [ 920]  array_test.js
    │   ├── [1.6K]  list_test.js
    │   └── [3.9K]  promise_test.js
    └── [ 238]  src
        ├── [ 683]  arrayRe.js
        ├── [1.8K]  listRe.js
        ├── [2.8K]  option.js
        ├── [2.5K]  promise.js
        └── [3.0K]  result.js

6 directories, 58 files

```

**Comment by imamatory** [comment]
Thanks for feedback. It seems you didn't link `bs-platform`. This lib uses`bs-platform` as a peer dependency. To start it separately you need to follow [contributing guide](https://github.com/planado/reason-commons#contributing)

**Comment by idkjs** [comment]
Missed that. Thanks.

```sh
 PASS  lib/js/__tests__/array_test.js (49.635s)
 PASS  lib/js/__tests__/list_test.js (49.727s)
 PASS  lib/js/__tests__/promise_test.js (49.801s)

Test Suites: 3 passed, 3 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        76.502s
Ran all test suites.
```
